language: python
cache: pip
# Existing Python versions
python:
  - 3.6
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install: pip install tox tox-travis
script: tox
