name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * 0" # weekly

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10]
        # exclude: #If you want to do this...
        #  - os: macos-latest
        #    python-version: 3.6:
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: python3 -m pip install tox==3.24.4
      - name: Run tests in tox
        # Run tox using the version of Python in `PATH`
        run: poetry run tox -e py
